### ISSUE TITLE
Log transformation

### ISSUE THREAD

**Issue by tknijnen** [isb-cgc/ISB-CGC-Webapp#303]
The log transformation is very handy, but I think that it should be log2 instead of log10. Expression values are usually log transformed using y = log2(x) + 1.

**Comment by s-paquette** [comment]
We do have plans to allow users to choose between log bases; we'll let you know here once it's live!

**Comment by Gibbsdavidl** [comment]
Also, after sharing a workbook, the option becomes unchecked.

**Comment by s-paquette** [comment]
This is a side effect of some other issues, mostly related to how we're not storing the checked/unchecked value of the log checkbox at the time. It should be fixed as a side-effect of enabling the option to choose log2 or log10.
