### ISSUE TITLE
Plots are off screen

### ISSUE THREAD

**Issue by Gibbsdavidl** [isb-cgc/ISB-CGC-Webapp#316]
On my laptop, and my desktop monitor, the plots are off screen.  Plots need to be smaller.

**Comment by s-paquette** [comment]
@Gibbsdavidl We did a lot of work on plotting in our last release; can you let me know if this is still happening when you have a chance?

**Comment by Gibbsdavidl** [comment]
Looks great! Feels very snappy. @s-paquette 

Only issue I see, and it's tiny, but for legends where points are colored by age, the points are colored differently for each age, like they are categories rather than a continuous color scale... great update though.  :-)

**Comment by s-paquette** [comment]
@Gibbsdavidl Thanks! I can put in a feature ticket for blocking ages in a range for color-by, since that would indeed be a bit more useful.
